spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/school
    username: postgres
    password: postgres

  flyway:
    url: jdbc:postgresql://localhost:5432/school
    user: postgres
    password: postgres

logging:
  level:
    root:
      info
    org:
      foxminded:
        debug
    # if we want so set debug level in root and avoid RMI logging
    javax:
      management:
        info
    sun:
      rmi:
        info
